config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get  'login' => 'sessions#new'
  post  'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/admin' => 'posts#admin'
  get '/admin/approoved_articles' => 'posts#approove_article'



  root "posts#index"





  resources :posts do
    resources :comments, only: [:create, :destroy]
    member do
    get  'author' => 'posts#unapprooved'
    get 'approoved' => 'posts#approoved'
 end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	validates :title, presence: true, length: {minimum: 5}
    validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email , uniqueness: true
# validates :password, presence: true, length: { minimum: 6 }
#  validates :password_confirmation, presence: true
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    post = Post.where(id: params[ :post_id]).first
    @comment = post.comments.create(comments_params)
    
    redirect_to post_path(id: post.id)
  end
  
  def destroy
    @post = Post.where(id: params[:post_id]).first
    @comment = @post.comments.where(id: params[:id]).first
    @comment.destroy

    redirect_to post_path(@post)
  end
  
  
  private
    
    def comments_params
      params.require(:comment).permit(:name,:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_post, except: [ :index, :create,:update]
  before_filter :authorize ,except: [ :index,:show]
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  # Assinging the current logged in user id to post id and creating post
  def create
    @post =  Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def show
    @post.count_view+=1
    @post.save



  end

  def edit

  end



  def update
    if @post.update_attributes!(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post.destroy

    redirect_to posts_path
  end


  def admin
    if current_user.role==1

    @post = Post.where(flagarticle:nil)
    else
     redirect_to 'posts'
    end
  end

  def approove_article
  @post = Post.where(id: params[:id]).first
    @post.flagarticle=true
    @post.save
    redirect_to admin_path
  end




  def unapprooved
  #debugger


  end

  def approoved
  #Sdebugger
    comment = Comment.where( id: params[:id] ).first

    comment.comment_review=true
    #debugger
    comment.save
   redirect_to posts_path
  end



  private
  def post_params
  	params.require(:post).permit(:title, :body)
  end

  def require_post
    @post  = Post.where(id: params[:id]).first


  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new

end
  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id


      redirect_to '/posts'
    else
      # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new

  end

  #create new users and save it in the database
  def create
    user = User.new(user_params)

    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/Signup/'
    end
  end







  private
#strong parameters
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
	<% if comment.comment_review==true %>
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	<% else %>
		"WAit for approoval"
    <% end %>
  </div>


</div>

app/views/comments/_comments.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <% if comment.comment_review==true %>
        <p class="comment_name"><strong><%= comment.name %></strong></p>
        <p class="comment_body"><%= comment.body %></p>
        <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
    <% else %>
        "WAit for approoval"
    <% end %>
  </div>
>

</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name%><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <button class ="button">
    <%= f.submit %>
    </button>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body align="center" >


<div id="main_content">
	<div id="header">
		<div id ="left" style="float:left;">
	    <button class="button" style="padding-top:0px" >
	    <%= link_to "Blog Home", posts_path %>
		
	    </button>

		</div>
		<div class="buttons">
		<button class="button"><%= link_to "New Post", new_post_path %>
		</button>
		<button class="button">
		  <% if current_user %>
			  Signed in as <%= current_user.name %> | <%= link_to "Logout", logout_path , :method => :delete  %>

		  <% else %>
			  <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
		  <% end %>
		</button></div>
	</div>
</div>






<% flash.each do |name,msg| %>
<%= content_tag(:div,msg,class:"alert")%>
<% end %>
</div>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div id="formpost" align="center">
  <fieldset style="width: 500px;">
  
    <legend><h1>Add Post</h1></legend>

    <%= form_for @post, url: posts_path, html: {class: 'form-horizontal'} do |f| %>
      <% if @post.errors.any? %>
        <div id="errorExplanation">

            <h2><%= pluralize(@post.errors.count, 'error') %> prohibited this post from being saved:</h2>

            <ul>
                <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
              </ul>
        </div>
    <% end %>
        <div class="control-group">
            <%= f.label :title, class: 'control-label' %>
            <div class="controls">
                <%= f.text_field :title, class: 'span4' %>
            </div>
        </div>

        <div class="control-group">
            <%= f.label :content, class: 'control-label' %>
            <div class="controls">
                <%= f.text_area :body, rows: '7', class: 'input-block-level' %>
            </div>
        </div>

        <div class="form-actions">
            <%= f.submit "Add Post", :class => 'btn btn-success' %>
            <%= link_to "Cancel", posts_path, :class => 'btn', :style => 'float:right;' %>
        </div>
    <% end %>
</fieldset>

</div>

app/views/posts/admin.html.erb
<% if current_user.role==1 %>
<% @post.each do |post| %>
<p><%=post.title %></p>
<p><%= post.body %></p>
    <%= link_to 'Approove',admin_approoved_articles_path( id: post.id),

                class: "button",
                data: { confirm: 'Are you sure?' } %>
<% end %>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper" align="center">
<h1> Edit post </h1>
<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<% if post.flagarticle==true %>

<div class="post_wrapper" align="center">
<h2 class="title"><%= link_to post.title, post %></h2>
<p class="date"><%= post.created_at.strftime("%B,%d,%Y")%></p>	
<hr>
</div>
<% end %>

<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper" >
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content" align="center">

    <% if @post.flagarticle==true %>

          <h3 style="color:darkred"><%= link_to 'Comments Waiting for approoval',author_post_path %></h3>



          <h1 class= "title" style="font-size:20px;"><%= @post.title %><h1>
            <p class= "date_and_author"> Submitted <%= time_ago_in_words(@post.created_at )%> ago

	

	 |      <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %></p>
	        <p align="center">
            <h3>viewed  <%= @post.count_view %> times</h3>
            <h2><%= @post.body %></h2>
            </p>
    <% else%>
            pending approval
    <% end %>




    <h3>Comments</h3>
    total comments: <%= @post.comments.count %>
    <%= render @post.comments %>
 
    <h3>Add a comment:</h3>
    <%= render 'comments/form'%>

    </div>
</div>

app/views/posts/unapprooved.html.erb
Owner id:<%= @post.user_id %>
Logged in user id :<%= current_user.id %>
<% if current_user.id.to_i==@post.user_id.to_i %>

    <% @post.comments.each do |comment| %>


        <% if comment.comment_review==false %>

            <p><%=comment.name %>
            <%=comment.body %></p>
            <p>
              <%= link_to 'Approove',approoved_post_path( id: comment.id),

                  class: "button",
                  data: { confirm: 'Are you sure?' } %>

                <%= link_to 'Delete', [comment.post, comment],
                               method: :delete,
                               class: "button",
                               data: { confirm: 'Are you sure?' } %>
            </p>


        <% end %>






    </p>
        <% end %>

<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>
    <p>
      <%= f.label :name%><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :email %><br>
       <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
    <p>
      <button class ="button">
        <%= f.submit %>
      </button>
    </p>
<% end %>

app/views/users/show.html.erb
<% @provide(title,@user.name) %>
<%= @user.name %>
<%= @user.email %>